[package]
name = "get621"
version = "1.2.1"
authors = ["nasso <nassomails ~ at ~ gmail {dot} com>"]
edition = "2018"

[dependencies]
tempfile = "3.0.7"
lazy_static = "1.3.0"
regex = "1"
scraper = "0.10.0"
glob = "0.3.0"
clap = "2.33.0"
chrono = "0.4.6"
reqwest = "0.9.14"
urlencoding = "1.0.0"
serde_json = "1.0.39"
