[package]
name = "get621"
version = "1.1.0"
authors = ["nasso <nassomails ~ at ~ gmail {dot} com>"]
edition = "2018"

[dependencies]
globwalk = "0.7"
clap = "2.33.0"
chrono = "0.4.6"
reqwest = "0.9.14"
urlencoding = "1.0.0"
serde_json = "1.0.39"
